{% set name = "CoastSeg" %}
{% set version = "1.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: 069d825d2ad2a24855b094e3d80589f88e43f694fd6301004f6dabff4fa07094

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - gdal >=3.8.4
    - h5py >=3.10.0
    - pytmd
    - coastsat-package >=0.1.74
    - area
    - aiohttp
    - chardet
    - dask-core
    - doodleverse-utils >=0.0.35
    - earthengine-api >=0.1.388
    - geojson
    - geopandas
    - jupyterlab >=3.0.0
    - leafmap >=0.14.0
    - nest-asyncio
    - xarray

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/SatelliteShorelines/CoastSeg
  doc_url: https://satelliteshorelines.github.io/CoastSeg/
  dev_url: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
