{% set name = "CoastSeg" %}
{% set version = "2.0.0" %}
{% set python_min = "3.10" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: 98f9df528fe44c2594c99c4b6d3b575632ef467b902606834d83168cdfc53d3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
    - hatchling
  run:
    - onnxruntime
    - pytz
    - netcdf4
    - numpy ==1.23.5
    - protobuf
    - python >={{ python_min }}
    - gdal >=3.8.4
    - h5py
    - pytmd <2.2.0
    - coastsat-package >=0.3.3
    - pooch
    - area
    - aiohttp
    - chardet
    - dask-core
    - doodleverse-utils >=0.0.35
    - earthengine-api >=0.1.388
    - geojson
    - geopandas
    - jupyterlab >=3.0.0
    - leafmap
    - nest-asyncio
    - xarray

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SatelliteShorelines/CoastSeg
  doc_url: https://satelliteshorelines.github.io/CoastSeg/
  dev_url: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
