{% set name = "CoastSeg" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: 2e7332ef46f4e39e14e12abbdb74bc8258ce5b886c17290d683786799711d48f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - pytmd
    - xarray
    - python >=3.9
    - aiohttp
    - area
    - chardet
    - coastsat-package >=0.1.23
    - dask-core
    - doodleverse-utils >=0.0.35
    - geojson
    - geopandas
    - ipyfilechooser >=0.6.0
    - ipywidgets >=8.0.6
    - leafmap >=0.14.0
    - nest-asyncio
    - tensorflow
    - tqdm
    - transformers

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Doodleverse/CoastSeg
  summary: An interactive jupyter notebook for downloading satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
