{% set name = "CoastSeg" %}
{% set version = "1.7.2" %}
{% set python_min = "3.10" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: 06ba19c6de044a46f7ff82a064dd6865e7fc96ac64918843a54ee9ec071776ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
    - hatchling
  run:
    - netcdf4
    - numpy ==1.23.5
    - protobuf ==3.20.3
    - python >={{ python_min }}
    - gdal >=3.8.4
    - h5py ==3.14
    - pytmd <2.2.0
    - coastsat-package >=0.3.3
    - pooch
    - area
    - aiohttp
    - chardet
    - dask-core
    - doodleverse-utils >=0.0.35
    - earthengine-api >=0.1.388
    - geojson
    - geopandas
    - jupyterlab >=3.0.0
    - leafmap ==0.35
    - nest-asyncio
    - xarray

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SatelliteShorelines/CoastSeg
  doc_url: https://satelliteshorelines.github.io/CoastSeg/
  dev_url: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
