schema_version: 1

context:
  version: 2.0.3
  python_min: '3.10'

package:
  name: coastseg
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/C/CoastSeg/coastseg-${{ version }}.tar.gz
  sha256: f307547bfa9b4a16cdabdf3aff59951a0f0644fe6815e3c4803651d941f7672b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - aiohttp
    - onnxruntime
    - chardet
    - dask-core
    - coastsat-package >=0.3.3
    - geojson
    - h5py
    - jupyterlab >=3.0.0
    - leafmap
    - nest-asyncio
    - pooch
    - protobuf
    - pytmd <2.2.0
    - xarray
    - pytz
    - netcdf4
    - geopandas
tests:
  - python:
      imports:
        - coastseg
      # bogus requirement on versioneer in doodleverse_utils
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  homepage: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: GPL-3.0-only
  license_file: LICENSE
  documentation: https://satelliteshorelines.github.io/CoastSeg/
  repository: https://github.com/SatelliteShorelines/CoastSeg

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
