schema_version: 1

context:
  version: 2.1.1

package:
  name: coastseg
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/C/CoastSeg/coastseg-${{ version }}.tar.gz
  sha256: 1d078cafc5b3dbb3145a1fa44f5b3beb4c2b1332be5632babe4edc63d88cb536

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - gdal
    # temporary pin needed because leafmap relies on ipyvuetify, but since conda-forge's ipyvuetify 3.0.0 build still pins ipyvue <2,
    # but it needs ipyvue >=3, this causes the Python metadata to be inconsistent (pip check fails). Remove this ceiling once 
    # conda-forge/ipyvuetify-feedstock fixes its ipyvue
    - ipyvuetify <3
    - aiohttp
    - onnxruntime
    - chardet
    - dask-core
    - coastsat-package >=0.5.0
    - geojson
    - h5py
    - jupyterlab >=3.0.0
    - leafmap
    - nest-asyncio
    - pooch
    - protobuf
    - pytmd >=3.0.9,<4
    - xarray
    - pytz
    - netcdf4
    - geopandas
    - timescale >=0.1.1
tests:
  - python:
      imports:
        - coastseg
        - coastseg.extracted_shoreline
        - coastseg.zoo_model
        - coastseg.common
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  homepage: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: GPL-3.0-only
  license_file: LICENSE
  documentation: https://satelliteshorelines.github.io/CoastSeg/
  repository: https://github.com/SatelliteShorelines/CoastSeg

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
