schema_version: 1

context:
  version: 2.1.2

package:
  name: coastseg
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/C/CoastSeg/coastseg-${{ version }}.tar.gz
  sha256: 184c3f17839ce992d097eca89f108b8e8805e1335890b3a978ac9922c2100c48

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - aiohttp
    - onnxruntime
    - chardet
    - dask-core
    - coastsat-package >=0.5.1
    - geojson
    - h5py
    - jupyterlab >=3.0.0
    - leafmap
    - nest-asyncio
    - pooch
    - protobuf
    - pytmd >=3.0.9,<4
    - xarray
    - pytz
    - netcdf4
    - geopandas
    - timescale >=0.1.1
tests:
  - python:
      imports:
        - coastseg
        - coastseg.extracted_shoreline
        - coastseg.zoo_model
        - coastseg.common
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  homepage: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: GPL-3.0-only
  license_file: LICENSE
  documentation: https://satelliteshorelines.github.io/CoastSeg/
  repository: https://github.com/SatelliteShorelines/CoastSeg

extra:
  recipe-maintainers:
    - 2320sharon
    - ocefpaf
